### ISSUE TITLE
[Bug] Cookies are stored permanently when using Dark Reader on iOS Safari in private mode

### ISSUE THREAD

**Issue by moenodedev** [darkreader/darkreader#11297]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Cookies are stored permanently while browsing in private mode on iOS Safari with Dark Reader enabled.

It may be an iOS Safari bug because cookies aren't saved on MacOS.

### Website Address

https://github.com/

### Steps To Reproduce

1. Enable Dark Reader for all websites in Safari on iPhone
2. Open https://github.com/ in a private tab
3. Close the Safari app
4. View website history in the Settings app to see that there's a cookie for github.com

### Expected Behavior

No cookies should be stored while browsing in private mode

### Actual Behavior

Cookies are stored while browsing in private mode

### Operating System

iOS 16

### Web Browser name and version

Safari

### Dark Reader version

1.4.2

**Comment by moenodedev** [comment]
@jensimmons where does this iOS Safari bug need to be reported?

**Comment by jensimmons** [comment]
It's be great if you can file it at feedbackassistant.apple.com

**Comment by moenodedev** [comment]
@jensimmons It's been reported to Feedback Assistant by many people over the past few years.

The bug affects all Safari extensions. Is there another place where the bug can be reported? It's easy to reproduce and fix.

**Comment by bershanskiy** [comment]
Thanks for the report, I was not aware of this bug on iOS. At this time I can provide only limited info:
 - this appears to be a Safari bug, not Dark Reader bug, as reported above. I'll test this and will bring it up in WebExtensions W3C CG (anecdotally, a couple bugs were resolved faster after they were discussed in CG)
 - Dark Reader does not access/read and does not modify/write cookies or any other forms of storage in tab contexts. Also, Dark Reader works fine with cookies disabled entirely.
 - iOS app is not part of this repo and it is not open source at this moment. It is a (hard/divergent) fork from this repo

**Comment by moenodedev** [comment]
@bershanskiy Advertisers are exploiting this functionality to get around Intelligent Tracking Prevention (ITP) but the behavior is intentional.

**Comment by BionicBison05** [comment]
Hi there, has anything changed since this issue was closed? I can confirm that the issue still exists today and it means I can’t use Dark Reader until it’s resolved.

**Comment by alexanderby** [comment]
Hi @BionicBison05, if I repeat the steps **1-3** and on step **4** go to **Settings -> Safari -> Advanced -> Website Data** I see no `github.com` in the list. Could you please provide other steps to reproduce the problem or tell where you see the cookies are being seen?

**Comment by BionicBison05** [comment]
In my testing, Dark Reader has to be explicitly enabled on the site (issue is not present if Dark Reader has an exception for the current site), and the website data comes from `githubassets.com`.
