### ISSUE TITLE
Dark Reader breaks Cloudflare Login

### ISSUE THREAD

**Issue by timmyRS** [darkreader/darkreader#1173]
https://dash.cloudflare.com/login

Logging in with Dark Reader in effect constantly shows the error "please refresh the page."

**Comment by dan-dr** [comment]
Same here!

**Comment by Richienb** [comment]
In the Developer Tools console, the following error appears whilst trying to log in:
```
POST https://dash.cloudflare.com/login 401 VM391 heap-3538148622.js:2
```

**Comment by pixelcookie11** [comment]
Same!

**Comment by DakotaLarson** [comment]
This is a critical error. I have been dealing with lackluster cloudflare support for the last week before I realized it's an extension on my side that shouldn't interfere with authentication. Please fix this.

**Comment by dan-dr** [comment]
If it's that important to you, you can fix it and send a PR. Or you can just disable it on cloudflare.

**Comment by DakotaLarson** [comment]
@dan-dr I don't have the first idea where to begin working on this codebase. Do you? My concern is more for the business type person who will use cloudflare for essential operations, be unable to login due to the bug, and not be able to solve as the solution isn't obvious.

**Comment by alexanderby** [comment]
I see this bug on some websites, usually some banking accounts. I think this could be some protection from extensions: the app detects changes to the DOM (e.g. placing stylesheet elements) and treats this like suspicious behavior.

Maybe adding DOM nodes shifts the index of some element, which contains some token, needed for login.

Also try using Filter mode, Dynamic mode can cause some errors by requesting CSS files and images without credentials that could be required, which can cause some servers to treat this like DDOS attack, or just a poorly written web app cannot handle multiple requests.

**Comment by Macley-Kun** [comment]
The issue still persists, it seems that using Static mode fixes it.

After logging in this way, switching back to Dynamic is ok.

Is someone able to make a pull for this? Overall the darkreader works amazingly well on almost every site! Excellent work!

**Comment by karolyi** [comment]
+1

**Comment by esa1975** [comment]
I've just figured this out after a week of thinking it was something Cloudflare changed on their end. The frustrating part is that it would work on rare occasions, so I didn't make the connection between DR and login forms. I'm not asking for it to be fixed necessarily but wanted to post something here so people are aware this is an issue.

**Comment by Gusted** [comment]
I will try to contact Cloudflare and see if we can work to a solution.

**Comment by Gusted** [comment]
That's ironic can't find 123 a public support email, you seems only can submit tickets if your are a user.
Than I'l suggest if you can open up a ticket with a link to this issue. 
Also if needed for anyone my e-mail is williamzijl7@hotmail.com (For any cloudflare support team watching)

**Comment by Richienb** [comment]
For some reason, it appears that the updated Cloudflare login page is actually compatible with Darkreader.

**Comment by Gusted** [comment]
Could the other users confirm this as well?
CC:
@timmyRS
@esa1975
@Macley-Kun
@karolyi 
@DakotaLarson
@pixelcookie11 
@dan-dr

**Comment by karolyi** [comment]
yep, can confirm.

**Comment by Gusted** [comment]
That's good than the issue is resolved :) I hope the other participant will get this notification and can use Dark Reader again.

**Comment by Macley-Kun** [comment]
I’ll check later o/ great to see this get resolved finnaly!

Met vriendelijke groet,

Wesley de Vree
________________________________
Van: Gusted <notifications@github.com>
Verzonden: Thursday, July 2, 2020 10:47:27 PM
Aan: darkreader/darkreader <darkreader@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [darkreader/darkreader] Dark Reader breaks Cloudflare Login (#1173)


That's good than the issue is resolved :) I hope the other participant will get this notification and can use Dark Reader again.

**Comment by esa1975** [comment]
> For some reason, it appears that the updated Cloudflare login page is actually compatible with Darkreader.

When was it updated? It was an issue this morning and it still appears to be now. Of course, I got a 529 error now, so I have to wait to try again.

@Gusted I will try again later and see if it's still an issue for me. Thanks for looking into this.

**Comment by DakotaLarson** [comment]
I was still having the issue on Firefox with the login page. Since first encountering this though, I have had issues like this on more than one page. Ultimately, injecting code into some brittle websites will have effects like this. 

Perhaps more documentation could be presented about this? Not sure what a solution would look like though since I doubt the first thing users are going to think of when something is broke is some obscure help doc from an extension that normally just works on most sites. 

Either way, the best fix for the user is to switch back to filter mode when problems are encountered.

**Comment by Gusted** [comment]
Seems 50/50 of its worked some people say new login page so I think it's just rolling out? You always can make a ticket with cloudflare as I can't reach them.

**Comment by karolyi** [comment]
So after confirming yesterday it worked from my OSX Chrome, I just confirmed again on my Windows desktop with Chrome, that it sill works.

Chrome is Version 83.0.4103.116 (Official Build) (64-bit)
Dark Reader is 4.9.13

just FYI

**Comment by Macley-Kun** [comment]
Tested it out, checkt first the if i had the same latest version (4.9.13) and i did. Same for Chrome.Did a logout, login twice with 2FA failing once. And everything worked as i expected. Using default settings (dynamic) thanks for fixing it! Going to unscribe from this issue! Thanks for making dark reader 😊 i hope one day darkreader can detect if a site has darkmode support, and disable it self for that site automatically. That would save me for ever touching darkreader’s settings  Van: László KárolyiVerzonden: vrijdag 3 juli 2020 07:56Aan: darkreader/darkreaderCC: Macley; MentionOnderwerp: Re: [darkreader/darkreader] Dark Reader breaks Cloudflare Login (#1173) So after confirming yesterday it worked from my OSX Chrome, I just confirmed again on my Windows desktop with Chrome, that it sill works.Chrome is Version 83.0.4103.116 (Official Build) (64-bit)Dark Reader is 4.9.13just FYI—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Gusted** [comment]
Yea I'm had some research and prototype of detected dark mode but it still need some tweaks as it won't always works. But glad that cloudflare new login is rolling out that works again

**Comment by queensferryme** [comment]
Hi, I'd like to report that this issue might come back again (sadly).

I am using Firefox 80.0 with Darkreader 4.9.16 (Version 5 Preview enabled), and when I try to login https://dash.cloudflare.com/login, I got a `Auth failed (Code: 10302)`. The bug exists in dynamic mode, but not in filter/filter+/static modes.

Also, similar bug reports have been found here (https://community.cloudflare.com/t/login-problem-auth-failed-code-10302/) within the latest 24 hours, where another user found the bug disappears after disabling the darkreader extension.

**Comment by Gusted** [comment]
Well, nothing we still can do as we are just adding modified styles. So it's more up to them to fix this issue rather than us changing the way we work.

**Comment by esa1975** [comment]
The workaround I am using is I have added https://dash.cloudflare.com/login and https://dash.cloudflare.com/two-factor (if using two-factor) directly to the sites list in Dark Reader. That bypasses it for these pages which allows me to log in. Once in the dash, it switches back to dark mode.

**Comment by Germs2004** [comment]
> Well, nothing we still can do as we are just adding modified styles. So it's more up to them to fix this issue rather than us changing the way we work.

You could add Cloudflare to a built-in "disabled" list.  This problem affects me today on Chrome and FireFox, so having Cloudflare automatically excluded by DarkReader would have avoided the issue.

**Comment by Gusted** [comment]
> You could add Cloudflare to a built-in "disabled" list. This problem affects me today on Chrome and FireFox, so having Cloudflare automatically excluded by DarkReader would have avoided the issue.

That's really just for dark-sites and not for `protected-sites` as they can still be used trough filter(+) and Static(with a [exported generated CSS](https://darkreader.org/blog/v4-9-16/)). 

>  so having Cloudflare automatically excluded by DarkReader would have avoided the issue.

If cloudflare just didn't shove that auth error under dark reader users, it would have avoided this issue as well 🤷🏽‍♀️.

**Comment by Macleykun** [comment]
Hey isn’t this fixed?

**Comment by Gusted** [comment]
I've been using cloudflare personally for my own site to test out some of their options and with darkreader didn't broke once. And if cloudflare still had a weird protection in place I sure as hell triggered it by now, ~~robots can't pass anti bot detection~~

**Comment by Germs2004** [comment]
I had the problem before, but it seems to be fixed now for me.
