### ISSUE TITLE
[Bug] Firefox ("Isolated") consumes 30-34 % of the cpu power

### ISSUE THREAD

**Issue by promeneur** [darkreader/darkreader#12231]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

firefox consumes 30-34 % of cpu power

After discussing with Firefox team and experimenting, it's clear that if we disable "dark reader" there is no more problem.

https://bugzilla.mozilla.org/show_bug.cgi?id=1877401

### Website Address

www.lefigaro.fr www.lemonde.fr

### Steps To Reproduce

Steps to reproduce:

go to [www.lefigaro.fr](http://www.lefigaro.fr/) or [www.lemonde.fr](http://www.lemonde.fr/)

stay on this page

wait

### Expected Behavior

Expected results:

Firefox consumes less CPU power.

### Actual Behavior

Actual results:

You see that "Isolated" consumes 30-34 % of CPU power

This occurs only with the home webpage.

### Screenshots

![30%_lemonde](https://github.com/darkreader/darkreader/assets/240424/b9d47f78-934a-4cc9-9547-8ed2fdde07e2)
![34%_lefigaro](https://github.com/darkreader/darkreader/assets/240424/26066a67-4917-4933-9b52-7b4b7aa7a4c2)

### Operating System

openSUSE Tumbleweed

### Web Browser name and version

Firefox 122

### Dark Reader version

4.9.76

**Comment by emilio** [comment]
(I maintain the Firefox style engine, and if dark reader is doing something that ought to be fast I'm happy to take a look)

**Comment by emilio** [comment]
Same if we could provide better APIs to make dark reader work better, etc.

**Comment by mehraneftekhari99** [comment]
I have the same issue. Here's screenshot attached from Firefox profiler. I don't know how to export from it, let me know if you need more data.
![image](https://github.com/darkreader/darkreader/assets/95145722/61f8686f-1a3c-4b44-9f11-4dfa2db77547)

The problem is observed in https://arxiv.org/abs/1907.06130

**Comment by Kostrol** [comment]
Chiming in with my experience, the other issue i commented got closed.

[Kooha-2024-01-28-03-23-51.webm](https://github.com/darkreader/darkreader/assets/38816613/64148a19-0177-4d65-97bb-f1dcd1b069b1)

Issues with high ram and cpu usage, certain video tabs on piped.video (youtube frontend) will suddenly start having issues, you can see in the top left how the CPU is affected (even reported above 100%) and also the excessive amount of memory that gets used when i do playback.

**Comment by alexanderby** [comment]
@emilio The problem is that Firefox doesn't allow extensions to access to Adopted Stylesheets. We have to inject a script into web page's context, attach wrappers around CSSStyleSheet prototype, pass css rules and text between page's context and extension's context and through events. This support was added recently, previously it didn't work at all. While I didn't see any performance issues, I fixed some bugs there and that could help. I would publish an update soon.

**Comment by reijerh** [comment]
Same here, couple of tabs @ 50-300% CPU.

Please see attached a captured trace for the archlinux.org tab.
[Firefox 2024-02-07 15.05 profile.json.gz](https://github.com/darkreader/darkreader/files/14194921/Firefox.2024-02-07.15.05.profile.json.gz)

**Comment by alexanderby** [comment]
4.9.77 has been released with some bug fixes for Firefox. Could you please check it is still happening for you?

**Comment by promeneur** [comment]
lemonde.fr good
lefigaro.fr good

leparisien.fr not fixed

**Comment by emilio** [comment]
I commented on https://bugzilla.mozilla.org/show_bug.cgi?id=1751346 about this.

**Comment by promeneur** [comment]
Thanks

**Comment by alexanderby** [comment]
I think Emilio meant my comments about Adopted Style Sheets. That bug, which caused errors being spawned was fixed. I see quite high CPU usage for this website in Chrome with Dark Reader disabled, so the issue could be the site itself, maybe some video of popping ads. https://www.leparisien.fr/

**Comment by promeneur** [comment]
With Firefox, I get 50 %
with Chrome, I get 30 %

with darkreader disabled

Firefox , 20 %
Chrome, 25 %

**Comment by zDEFz** [comment]
Same issue. "Isolated" is consuming the most CPU in my system.

**Comment by promeneur** [comment]
Today at www.lemonde.fr with Firefox I get the problem again.

The problem is not fixed and is a random one.

**Comment by zDEFz** [comment]
> Today at [www.lemonde.fr](http://www.lemonde.fr) with Firefox I get the problem again.
> 
> The problem is not fixed and is a random one.

You know you can "fix" this by setting stuff in about:config... from https://gist.github.com/RubenKelevra/fd66c2f856d703260ecdf0379c4f59db 

```
fission.autostart = false 
privacy.partition.network_state	= false 
dom.ipc.processCount = 1
dom.ipc.processCount.webIsolated = 1
```

**Comment by promeneur** [comment]
@zDEFz 

thanks

**Comment by emilio** [comment]
That is terrible advice both performance and security wise. It makes all tabs run in the same process.

**Comment by zDEFz** [comment]
> That is terrible advice both performance and security wise. It makes all tabs run in the same process.

So what? It stops making the cpu run on 100% all the time and consumes far less memory.
Even if it is slower, it is better than the system being no more actionable.
Maybe it helps me more as I don't use more than 3 tabs in general but have many windows?
Way to judge.

**Comment by promeneur** [comment]
My CPU is an intel I3-12100 and the ram size is 16 GB.

In my case, Firefox consume 30-35 % when the problem occurs. 
When the problem does not occur, Firefox consumes 0-5 %.

 This problem occurs a little time compared to the time I use Firefox. Most of the time I did not encounter the problem, even with many tabs.

It is certainly a waste of CPU power, but it is not critical. This does not freeze Firefox or the OS.

I can wait for a fix.

**Comment by alexanderby** [comment]
I see this `[www.lemonde.fr](http://www.lemonde.fr/)` consumes a lot of CPU when starts playing a video from just scrolling over the page. That causes around 50% CPU usage on M1 chip without Dark Reader enabled.

**Comment by reijerh** [comment]
Quick tip for if you're still having trouble, this is how I recorded profile info (this helps out the devs):

In Firefox:
1. F12 to open dev view at bottom of screen
2. Click the 'Performance' tab
3. Click 'Start recording'
4. Wait a couple of seconds, click 'Capture recording'
5. In the newly opened tab, click 'Upload local profile' at the top right of the page
6. Click 'Download'
7. Attach the downloaded file to a comment here (just drag it into the text box).

**Comment by outfrost** [comment]
I'm seeing stylesheet-related high CPU usage on 4.9.77, with a slight twist.

Launching Firefox normally, having it restore all my previous tabs and load them, with Dark Reader enabled, everything seems fine. 50+ tabs, no problem.

In my session, I have some tabs with Google services, for which Dark Reader is enabled - calendar.google.com/calendar, docs.google.com/document, docs.google.com/presentation, drive.google.com/file

If I leave Firefox open, and suspend the machine, then wake from suspend a while later (hours+), an Isolated Web thread for `https://google.com` starts consuming 100% of a logical CPU core. This continues until I do one of the following:
* close and reopen all affected Google service tabs; or
* restart Firefox.

If I disable and re-enable Dark Reader from the addons manager, initially, the CPU usage goes away, however, none of the configured dark styles are actually applied to already open tabs. Once I disable and re-enable dark style for a particular website in Dark Reader, the CPU thrashing resumes.

This is on Firefox 122.0.1 Snap for Ubuntu 22.04.

**Comment by reijerh** [comment]
Here's another trace FF 122.0.1, Dark Reader 4.9.77

[Firefox 2024-02-21 12.50 profile.json.gz](https://github.com/darkreader/darkreader/files/14359062/Firefox.2024-02-21.12.50.profile.json.gz)

![image](https://github.com/darkreader/darkreader/assets/136743/fc73641c-544a-4dbe-a184-8edb6846ba5a)

**Comment by promeneur** [comment]
Another site with the problem

https://www.isabelleetlevelo.fr/2024/02/26/train-velo-toujours-aussi-malmene/

Isolated consumes 25 %.

**Comment by iamkroot** [comment]
For me the issue occurs when I add the `INVERT` rule for an element.

Webpage: http://cs341.cs.illinois.edu/coursebook/Ipc#visualizing-the-dereference

The images aren't visible on dark mode, so I added the following rule via Dev Tools-

```
cs341.cs.illinois.edu

INVERT
.img-paragraph>img
```

But as soon as this gets added, the CPU usage shoots up.
Here's a call graph screenshot:
![callgraph](https://github.com/darkreader/darkreader/assets/29517049/fbc72736-1033-4ba2-8f09-3229cf724be2)

Looks like it is repeatedly re-rendering the page via `requestAnimationFrameOnce`?

**Comment by liar666** [comment]
Some context first:
- I have a laptop (Dell) that I connect on a Dock when I am in my office and disconnect when I'm in meetings (several times a day). Every time I disconnect the computer from the dock, the network switches from Eth+Wifi to Wifi-only/no-Net (and conversely)
- I almost never switch off my computer, only put it in suspend

Just living in such an environment, I very often get at least one FF Tab that go berserk and uses all CPUs. When killing the faulty Process (the tab indicates "Crashed"), another one takes over and uses all CPUs , etc. Until I kill 5/6 processes/tabs.

Just disabling DarkReader solves everything.

**Comment by liar666** [comment]
More info from my side: the (very) high CPU usage seems to come from some cloudflare "challenge" URL. Not sure how it is related to darkmode...

![screenshot_2024-03-25-14 49](https://github.com/darkreader/darkreader/assets/3216927/90f3e1d8-70b7-4268-8768-9ded55298e08)

**Comment by alexanderby** [comment]
@iamkroot Thanks for spotting this. I made a small but important fix https://github.com/darkreader/darkreader/commit/caf0ad23897a2b4f530f5ec5c3902eaa32fb2545

Probably that was the reason for random performance issues when the computer is waking up. The fix will be published after the Easter.

**Comment by iamkroot** [comment]
> @iamkroot Thanks for spotting this. I made a small but important fix [caf0ad2](https://github.com/darkreader/darkreader/commit/caf0ad23897a2b4f530f5ec5c3902eaa32fb2545)
> 
> ~Probably~ Definitely that was the reason for random performance issues when the computer is waking up. The fix will be published after the Easter.

Excellent, thank you very much for acting on the report! Does this fix the other perf bugs reported on this page?

**Comment by alexanderby** [comment]
The fix for a wake-up and dev tools problems should be already available in version 4.9.81. Regarding the other websites, I don't see any issues with Dark Reader. Le Figaro uses JW Player that causes 25% CPU usage when auto-plays a video and 5% when being idle.

Please share some links to slow web pages if you see any.

**Comment by iamkroot** [comment]
Thanks again, the site I reported is fixed! I have definitely seen the degradation elsewhere too. But unsure if we already had custom rules for them and that caused the issue, will verify next time I hit something.

**Comment by promeneur** [comment]
I tested all the sites I reported. No more problem.

thanks

**Comment by alexanderby** [comment]
Wonderful. Please submit a new issue if you notice any problems.
