### ISSUE TITLE
Doesn't work with local PDF files

### ISSUE THREAD

**Issue by orionflame** [darkreader/darkreader#12965]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Hi,

Like here: https://github.com/darkreader/darkreader/discussions/8488

I also started seeing this recently. I have the allow accessing local files option turned on but dark reader says the page is protected. How can I fix this?

![image](https://github.com/user-attachments/assets/5247db07-fd0b-41eb-a8b5-1d354b4e3cef)

### Website Address

N/A

### Steps To Reproduce

Open a local PDF using chrome 

### Expected Behavior

It should color PDF to dark

### Actual Behavior

PDF colors are white like before the extension

### Operating System

Windows 11

### Web Browser name and version

Chrome Version 126.0.6478.127 (Official Build) (64-bit)

### Dark Reader version

Latest

**Comment by orionflame** [comment]
thx alot. it would be the same in edge? if not i will install firefox just for this.

**Comment by orionflame** [comment]
OK I just tried the steps you showed in firefox but it still doesn't show in dark mode unfortunately. It says "can't read or change data on this site" and it shows PDF in that place in OP where it says "about".

Not sure if I am missing something. It's brand new firefox.

**Comment by alexanderby** [comment]
Did you enable "Enable for file URLs" option in `chrome://extensions` page?

**Comment by Sbrjt** [comment]
@alexanderby

**Comment by Break-Ben** [comment]
I also had this same issue recently even though it worked for a long time, enabling the PDF file option in the dark reader settings mostly fixed it for me.
![image](https://github.com/user-attachments/assets/542e7ddd-aeb8-421a-846b-c5179e6724b0)

However, enabling this still shows PDFs as 'about:' in the extension with the red protected message below it, and it cannot be toggled by pressing the 'about:' button (I used to be able to toggle it by pressing that button that instead said 'PDF').
![image](https://github.com/user-attachments/assets/f6a4feab-05a6-4357-9696-07681798fdb6)

**Comment by mdeweerd** [comment]
This works on Chrome but because something recently changed I had to follow the suggestion by @Break-Ben to enable it again.

**Comment by Menghini** [comment]
I am having this same issue right now with Brave.

**Comment by msxdan** [comment]
Additionally to @Break-Ben message, I had to enable `Advanced/Enable on restricted pages` to make it working

![image|300](https://github.com/user-attachments/assets/631812b1-748a-42e3-b72f-de14dd2d353c)

**Comment by Gooberpatrol66** [comment]
I'm using darkreader 4.9.99 and the "enable for pdf files" option is not present.

**Comment by Gooberpatrol66** [comment]
> Go to Dark Reader's Settings>Advanced>Enable on restricted pages.

Done

> And also, Settings>General>Enable for pdf files.

Not there. I'm using firefox 135 btw

**Comment by FlynnSpace** [comment]
I success on my Edge. Dark Reader's Settings is not enough! Try Edge extension>Dark Reader's Settings>Click Manage Extensions>choose Allow access to file URLs. This method works for me.

**Comment by FlynnSpace** [comment]
BTW, if you like Edge and want to take some notes on pdf, you can try extension "easy pdf viewer". It also have dark mode, and easy to take notes.

**Comment by excessivegravitas** [comment]
Is there a way to get both the background and the PDF itself rendered dark?  Seems silly to have "dark mode" brighten the background up.

**Comment by Break-Ben** [comment]
> Is there a way to get both the background and the PDF itself rendered dark? Seems silly to have "dark mode" brighten the background up.

Personally I switched to the [doqment extension](https://github.com/shivaprsd/doqment) for viewing PDFs a while ago. I generally wouldn't recommend different software as a solution to a problem, but it's nearly been a year since this issue was opened and I still get notified about it every now and then so hopefully this can help some people!

**Comment by Menghini** [comment]
> > Is there a way to get both the background and the PDF itself rendered dark? Seems silly to have "dark mode" brighten the background up.
> 
> Personally I switched to the [doqment extension](https://github.com/shivaprsd/doqment) for viewing PDFs a while ago. I generally wouldn't recommend different software as a solution to a problem, but it's nearly been a year since this issue was opened and I still get notified about it every now and then so hopefully this can help some people!

Than you for sharing. I'm in the exact same boat as you, @Break-Ben. I just downloaded this and will use it for PDFs. Much appreciated!

**Comment by mdeweerd** [comment]
Google decided "to break this" (by indirect choices) - I just got a message indicating that Google Chrome is improving the PDFs or so and Dark Reader is not inverting them anymore - neither online or local...

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```

**Comment by mdeweerd** [comment]
@luo-chuan Thank you for the alternatives.
However, I did not find "PDF Reader" for chrome, only multiple extensions containing "PDF Reader" in their title.  As your HTML shows "pdfViewer", I installed "PDF Viewer", but that does not have the suggested option to add some HTML.

I found that we can add CSS in the Dark Theme's parameters.  While I did manage to impact the presentation of regular html pages, I did not succeed with the "PDF Viewer" extensions nor the "internal" extension from Google (which uses an iframe and shadowroot).

<img width="951" height="635" alt="Image" src="https://github.com/user-attachments/assets/3ae58ba6-d807-4779-aec1-124dc19c02d7" />

**Comment by luo-chuan** [comment]
> However, I did not find "PDF Reader" for chrome.

Click this [link](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl). The extension is renamed to "PDF Reader and Editor" now. And don't forget to allow this extension to run on local file and private mode.

Set the extension like this,

<img width="701" height="451" alt="Image" src="https://github.com/user-attachments/assets/a4a2af32-541a-400b-bb9a-edc55118884d" />

**Comment by Razzy76** [comment]
> I success on my Edge. Dark Reader's Settings is not enough! Try Edge extension>Dark Reader's Settings>Click Manage Extensions>choose Allow access to file URLs. This method works for me.

This worked for me on Microsoft Edge!  Thanks.

**Comment by zuglah** [comment]
You can simply create a bookmark then, as URL, set : 
`javascript:(function(){var v=document.querySelector('#viewerContainer');if(v){v.style.filter=v.style.filter?'':'invert(1)%20hue-rotate(180deg)';}})();`

Everytime you read a PDF, if you like to invert color, just click the bookmark.

**Comment by hrfried** [comment]
I've done this many ways over the past few years but while checking if this was fixed or not, I realized I should share what I found to be the most decent and keyboard-centric workaround...one that doesn't require allowing all addons the ability to run on protected sites (braindead on Mozilla's part for this nonsense, while still lacking dark mode on pdfs and half of their own websites in 2026....)

Make a bookmark, set below (or your preferred bookmarklet script) in URL:

`javascript:(()=>{const el=typeof viewer!=='undefined'?viewer:document.body;el.style.filter=el.style.filter?'':'grayscale(1) invert(1) sepia(1) contrast(75%)';})()`

Give it the keyword `d`

then  `alt+d_d_enter` will quickly toggle PDF, mozilla internal sites, (or anything else) between the simple dark mode and normal mode.

Initial `alt+d` brings you to the address bar (and automatically selects all existing text), `d` is the keyword for the bookmarklet, and enter completes it. You could set a couple of these shortcuts if you wanted..

I'm sure there are better js bookmarklet functions to pass, but this is good enough for me. Would work the same way with any bookmarklet script.

Usually when this annoys me the most is when I'm browsing late at night and get blinded by a PDF or protected page. I can do this keyboard shortcut in probably 100ms, and I'm usually not that worried about good image fidelity or contrast...I just want to not be blinded, lol. Hopefully useful for someone else!
