### ISSUE TITLE
dark reader hides images; is it possible to make them reappear?

### ISSUE THREAD

**Issue by rinaldi6109** [darkreader/darkreader#1520]
On this site: https://www.ecodibergamo.it/ Dark Reader hides imahes on the left (scroll down the page). I've read readme.md content but I've not understood if it is possible to add a css rule om Dark Reader > More > Tools to make them reappear. Is there any good soul who can give an hint? Thank you.

**Comment by jtraub** [comment]
Please post a screenshot of the site with DarkReader enabled and another one with DarkReader disabled so we can see the problem.

**Comment by rinaldi6109** [comment]
I just realised, using a new profile to do the screenshots, that the issue depends on ShadowFox. Sorry for troubling you. 
Unfortunately I'm using both (Dark Reader and ShadowFox) and there are some annoying problems. For this one I'm going to open an issue there (ShadowFox).

**Comment by rinaldi6109** [comment]
Wait! No! I got confused. I missed to hit "refresh page". It's Dark Reader fault!
Version with Dark Reader disabled:
![immagine](https://user-images.githubusercontent.com/1431515/63647970-f84e2180-c728-11e9-947e-e194f03109b8.png)
Version with Dark Reader enabled:
![immagine](https://user-images.githubusercontent.com/1431515/63647983-1ae03a80-c729-11e9-8703-164daa83e2aa.png)

**Comment by jtraub** [comment]
I can not reproduce it both on Firefox and Chrome

**Comment by rinaldi6109** [comment]
Excuse me. :( It's my fault, but I don't understand why.
Before I have written: a new profile. Honestly, I've copied all the content of my previous profile folder to a new one, then deleted all history data, then deleted all addons apart Dark Reader, but the result is the same.

**Comment by jtraub** [comment]
The best way to test is to create a new profile and install only DarkReader in it.

Make sure that you hit refresh button after you load the site for the first time and enable DarkReader there. Also please let us know your Firefox version.

**Comment by rinaldi6109** [comment]
> The best way to test is to create a new profile and install only DarkReader in it.

Yes I know, I worked more to be sure (sigh!) that any ather addons could not interfere.

> Make sure that you hit refresh button after you load the site for the first time and enable DarkReader there. Also please let us know your Firefox version.

FF 68.0.2

**Comment by addeps3** [comment]
Same problem on Google images while using static mode on Firefox mobile 68.02 android 7.0.
Work around solved it by setting individual website to dynamic.

**Comment by Gusted** [comment]
Hi their!

I got the same results with Static theme but It appears that after 3-5 seconds the image loads. Can you comfirm this is for you as well?

Regards,
Gusted

**Comment by rinaldi6109** [comment]
I have no problem using google images with FF on android.

**Comment by Gusted** [comment]
I meant https://www.ecodibergamo.it/ On PC

**Comment by rinaldi6109** [comment]
No, they don't load, even after a bunch of seconds.

**Comment by Gusted** [comment]
Should be fixed.

**Comment by jstephens9245** [comment]
just started happening, fixes itself if I disable and re-enable, but fails again if I re-load

![image](https://user-images.githubusercontent.com/16173550/99845096-17ad4780-2b42-11eb-8239-7ee2b2f3f590.png)

**Comment by Gusted** [comment]
> just started happening, fixes itself if I disable and re-enable, but fails again if I re-load
> 
> ![image](https://user-images.githubusercontent.com/16173550/99845096-17ad4780-2b42-11eb-8239-7ee2b2f3f590.png)

That's another issue, it seems like Dark Reader's fallback style is still applied that is an basic style to provide dark colors, however it seems like it isn't being removed. You can open up a new issue if this issue persist.

Regards,
Gusted

**Comment by LikhithRajT** [comment]
It looks like I've found the solution:
    Turn off "Change font" settings
         If Preview new design is selected :
            See all options > Font & more > Change Font: No
            Like So : ![image](https://user-images.githubusercontent.com/47000780/109141985-54fa2480-7784-11eb-9a5e-854ac84f6bf8.png)

         If Preview new design is not selected :
            More > Click the Check mark on the left of that font name to turn it into "X" 
            Like so : ![image](https://user-images.githubusercontent.com/47000780/109141757-19f7f100-7784-11eb-8294-10491d110f2c.png)

**Comment by pdonias** [comment]
I'm still seeing this on Firefox. Some (not all) websites have their images hidden by Dark Reader.

![Capture_2021-03-30_16:42:11](https://user-images.githubusercontent.com/10992860/113008359-40d88700-9177-11eb-8574-6f9c753ec8b0.png)

Should this issue be reopened?

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/1520#issuecomment-731385552
