### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by a7hybnj2** [darkreader/darkreader#2022]
I hope this breaks through the 100's of issues that are already posted. I am using a clean install of firefox with this extension on macOS(10.15.3). When I load certain pages like this [one](https://www.fujitsu.com/us/products/computing/peripheral/scanners/scansnap/sv600/index.html) then the 'firefoxCP webextension' process goes to 100% usage. I can then disable the addon and restart firefox and it doesn't happen.

I don't know if something on that page is causing it but it happenes everytime I try it.

- Load the page above
- enable darkReader
- reload(f5) the page
- Watch it hang

**Comment by trungducng** [comment]
Same issue. I use Google Chrome in windows 10. The solution is uninstall this extension till it is fixed

**Comment by pz239** [comment]
Same issue. This extension slows down the firefox, and I will change to an alternate.

**Comment by Gusted** [comment]
#535

**Comment by Gusted** [comment]
This a know issue with Firefox and memory addressing. As for darkreader we only can push improvements but this issue will still persist probably, other firefox addons have problems with this also..

**Comment by trungducng** [comment]
Not only Firefox, issue occurs in Chrome as well

**Comment by Gusted** [comment]
> Not only Firefox, issue occurs in Chrome as well

Hmm,

I reloaded this site both with darkreader on and off.
I have a 2.5Ghz Intel pentium N4200 quadcore with 8 threads
They both spiked around 75% on and off and now while typing this with darkreader on it's only around 10-20%
Is the overal usage of the CPU 100% or just the Browser process.

**Comment by a7hybnj2** [comment]
So...I haven't done anything but I no longer have this problem. Things that have happened that may have effected it:

Several macOS updates.  
Reinstalled firefox (I borked it messing with something else).  
Removed all the add-ons I wasn't using anymore.
Also, I am pretty sure dark reader has had an update or 2 since I filled.

I am not going to close this issue because it seems like plenty of other people are have the same thing. Just, I haven't had it happen in over a month now.

**Comment by Gusted** [comment]
> So...I haven't done anything but I no longer have this problem. Things that have happened that may have effected it:
> 
> Several macOS updates.
> Reinstalled firefox (I borked it messing with something else).
> Removed all the add-ons I wasn't using anymore.
> Also, I am pretty sure dark reader has had an update or 2 since I filled.
> 
> I am not going to close this issue because it seems like plenty of other people are have the same thing. Just, I haven't had it happen in over a month now.

That's fine to hear! Maybe the other 2 also need to update and reinstall and remove non using add-ons

**Comment by Gusted** [comment]
A lot of improvements had been pushed in the lastest version 4.9.9 please check if the CPU is now `milder`

**Comment by a7hybnj2** [comment]
I actually haven’t been plagued by this issue for the last version either. I left the issue open because it seemed like other people were still having issues.

**Comment by Gusted** [comment]
Than OP's issue has been resolved :)
