### ISSUE TITLE
[BUG] Dark Reader's invert's Chrome webpage colors right away on startup, even if the extension is turned off

### ISSUE THREAD

**Issue by Mancerrss** [darkreader/darkreader#4069]
### **Describe the bug**

Upon every Chrome startup, even when the extension isn't set as "On", the webpage that shows up renders invertedly. And it's not even the same settings as the Dark Reader. It's an unpleasant webpage experience

### **Steps to reproduce**

- Go to Chrome "Settings" > On Startup > Check "Continue where you left off"
- Left an article or webpage to show up on Chrome when it starts up again
- Turn "Off" Dark Reader
- Quit the Chrome and restart it again

### **Expected behavior**

If the extension is set off, and it's set to "Off" or even "Auto" (even if it's still not the time, by Chrome startup it should never renders inverted to Dark Mode webpage under any circumstances. And not even hog the performance of the browser.

### **Actual behavior**

You'll see the webpage renders in an inverted way, before it goes back to normal (Light) only for like 5 seconds. Very unpleasant experience.

### **Screenshots**

Here is the screen capture of the problem :
https://youtu.be/mc7gHCkAaFw

### **System Information:**
 - OS: macOS Catalina 10.15.6
 - Browser: Chrome 86.0.4240.183 (Official Build) (x86_64)
 - Dark Reader version: Version 5 Preview (4.9.22)

### **Additional context**

PS suggestion : 
It it's set to auto or timed setting (sunset or sunrise time) if Dark Reader :

1.  Detects that it's time to go Dark again by set time (sunset)
2. Detects that it should render this webpage to Dark Mode, because it doesn't have native setting about it.

It should transition and render the webpage smoothly by a 1.5 seconds fade to Dark Mode rendering. 
Much better if we'll have customization to the time of the transition animation too.

### **Thanks**

**Comment by Mancerrss** [comment]
Just noticed too, sometimes the same appearance would appear, even when you're just switching tabs. 

It appears the behavior is triggered on some tabs that's haven't been visited for a few moments from now. Discarded tabs.

**Comment by Gusted** [comment]
Hi @Mancerrss!

This behaviour is being caused by the fallback style which was created to prevent `white flashes`. However 1 big con of this, it doesn't care if the extension is off or the current site is light it just does it thing because due to performance reasons we can't request the necessary settings for this.

HOWEVER! this rare case is fixed by #3921 which will check *chrome only* if the extension is off or not.

> It appears the behavior is triggered on some tabs that's haven't been visited for a few moments from now. Discarded tabs.

Standard practice for browsers to clean tabs that hasn't been used so it can be freed from memory and opening on those tabs will be treated as a new tab opening.

Regards,
Gusted

**Comment by Mancerrss** [comment]
Okay. I understand. Not an engineer or developer, just a UX designer. I don't know how is this implemented right now on Dark Reader. But I will suggest an implementation UX suggestion.
 
It seems that the `white flash` implementation, looks like an invert color / high contrast accessibility filter on the browser? Is it?

So what if, since that `white flash` implementation can't access the default webpage settings of Dark Reader, I suggest either of these implementation : 

-  Modify the `white flash` theme style. For a closer, much smoother transition to the real Dark Reader theme, few seconds later.
    -  Make the stroke borders, white fills or elements, fill with a lighter grey color instead. 
    -  The text stays white. 
    - The default background stays dark grey.
    - So when it switches to the real Dark Reader theme, it's as close as it can get to the real standard of color contrast adjustment when designing / inverting webpages to Dark Mode theme.

or

- Update the `white flash` style, whenever Dark Reader's default settings gets modified. 
  - Whenever user modified, updated Dark Reader's default `text color` and `background color`
     -  it carries over and modifies to the `white flash` style immediately.
   - No need to call for the Dark Reader settings in itself for performance issues. When it can call it's simpler, seperate style settings instead.

This is not the biggest rendering bug right now on the Dark Reader of course, but it will enhances trust of the user to the inversion process of the extension, when it's filtering experience / transition is as smooth and consistent as ever. 

Better inversion rendering experience = better webpage experience = better extension experience

Thanks.

**Comment by Gusted** [comment]
> It seems that the white flash implementation, looks like an invert color / high contrast accessibility filter on the browser? Is it?

The white flash is rather an behavior that's happening when a browsers switches to another website and the render engine renders a `white blank page` between the removing of all elements of the old website and loading the new website. We try to prevent this with injecting ASAP an Style that prevents this.



> * Modify the `white flash` theme style. For a closer, much smoother transition to the real Dark Reader theme, few seconds later.
>   
>   * Make the stroke borders, white fills or elements, fill with a lighter grey color instead.
>   * The text stays white.
>   * The default background stays dark grey.
>   * So when it switches to the real Dark Reader theme, it's as close as it can get to the real standard of color contrast adjustment when designing / inverting webpages to Dark Mode theme.
> 
> or
> 
> * Update the `white flash` style, whenever Dark Reader's default settings gets modified.
>   
>   * Whenever user modified, updated Dark Reader's default `text color` and `background color`
>     
>     * it carries over and modifies to the `white flash` style immediately.
>   * No need to call for the Dark Reader settings in itself for performance issues. When it can call it's simpler, seperate style settings instead.

This can be worked out as it's now by default a bit more black-ish and later it's getting back to the user preffered theme.
Do you have any suggestions for the colors, the current one is:
```CSS
html, body, body :not(iframe) { 
    background-color: #181a1b !important; 
    border-color: #776e62 !important;
    color: #e8e6e3 !important; 
}
```

Regards,
Gusted

**Comment by hjek** [comment]
> However 1 big con of this, it doesn't care if the extension is off or the current site is light it just does it thing because due to performance reasons we can't request the necessary settings for this.

This issue still happens when the extension is toggled off globally, not just for a specific site.

![flash-of-dark-content](https://user-images.githubusercontent.com/11958965/118468671-4d07ac00-b705-11eb-8cbe-a456b2203f5e.gif)

**Comment by Gusted** [comment]
> This issue still happens when the extension is toggled off globally, not just for a specific site.

This will be a non-issue once we can have dynamic content scripts, see #3921 we currently cannot disable content scripts.

**Comment by mystiquewolf** [comment]
I also experience this issue in Firefox. On open of browser page loads dark and after 3-4 seconds it changes to light background.

I also have parts of pages like Google Search for example showing black and then switching light. For example in Google Search right after loading the page the phrase "About 1 000 000 000 results found" is black, then it turns to light with animation/transition.
You can see screencast in this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1719660#c0

**Comment by Gusted** [comment]
> I also experience this issue in Firefox. On open of browser page loads dark and after 3-4 seconds it changes to light background.

3-4 Seconds? That should be way way earlier. Ill be looking into minimizing that.



> I also have parts of pages like Google Search for example showing black and then switching light. For example in Google Search right after loading the page the phrase "About 1 000 000 000 results found" is black, then it turns to light with animation/transition.

That's a weird issue, but also a issue that is explain-able and really a non-worthy to fix in my eyes.

That element has indeed transition on property. So if it changes background-color it will transition to that new color. We of course override to not do that. But considering we don't want to touch parts other than color-related stuff it could mess up(as it's only temporary).

**Comment by mystiquewolf** [comment]
I believe GMail has this 3-4 seconds in a pinned tab after opening Firefox (on startup).

**Comment by now-im** [comment]
Facing the same problem in Firefox version 98.0.2. 
Operating System: Arch Linux(KDE)
Dark Reader: 4.9.47

**Comment by flying-sheep** [comment]
This makes Dark Reader unusable even in allowlist-mode. I don’t want github to have a black flash before its perfectly fine native dark mode applies.

**Comment by Gusted** [comment]
Closing this issue, because this is technically not possible to fix, because due to to MV3 we're not able to merge https://github.com/darkreader/darkreader/pull/3921

**Comment by flying-sheep** [comment]
I want to turn off the fallback, how?

**Comment by Gusted** [comment]
You would need to modify dark reader's code for that. We technically cannot provide a option to disable it. Otherwise the fallback doesn't work(it has to be loaded ASAP and not wait 25-50ms to fetch user settings)

**Comment by flying-sheep** [comment]
Is there no firefox-specific way to do any of those things? I know that Chrome’s MV3 is neutered crap, but Firefox has a few things that enable synchronous code to run AFAIK.

**Comment by Gusted** [comment]
The mentioned PR was essentially made for chromium, Firefox support isn't as good. Knowing Firefox I don't like to rely on API's that are _marked as deprecated_ which can in any release just be removed.

**Comment by flying-sheep** [comment]
I didn’t have any specific APIs in mind, I just know that firefox devs are responsive to the needs of addon developers. If you need something, discussing it with them might help.

**Comment by Gusted** [comment]
I'm sorry, but that not how major of my experience has been with the Firefox devs that had to handle addon bug reports from me. Yet still, I don't have any leg to stand on, as my only argument is: "don't make this API go disappear, because we're using it as a hack for another hack" which is really no justification to not remove a API. Preferably browsers would not be _shitty_ and put some more work to prevent white flashes(Firefox does a better job at it than chrome) so we don't have to do that ourselves.

**Comment by flying-sheep** [comment]
I think having a good use case helps yes. “Synchronously read a user setting and then synchronously inject CSS before the page renders” is a good use case, no? So if you don’t have both APIs necessary for those steps, that could be reported, I think.

**Comment by chelseaawrence** [comment]
At last, a reliable and effective service I can rely on! I can only imagine how many people are struggling with crypto-related issues and are likely also unsure of their ability to find practical solutions. This is where jamesmckaywizard Recovery rightfully enters the picture as the best provider of the service, and their success is clearly demonstrated by the fact that they were able to help me recover 550,000 EUROS that I had lost to online cryptocurrency theft. Get in touch with them now if facing same loss chanllenges: Email addresses:jamesmckaywizard at gmail dot com or WhatsApp +31622647750. Kindly reach on these given details.
