### ISSUE TITLE
[BUG] Firefox Nightly partially works with Dark Reader

### ISSUE THREAD

**Issue by Magicool-1** [darkreader/darkreader#5182]
# Bug Report

## Describe the bug
Since todays Firefox Nightly update 88.0a1 (2021-03-05) (64-Bit) Dark Reader does not work anymore/only works partially on many websites

## Steps to reproduce

  An example of this is:
  - Visite websites such as:
https://github.com/
https://gmx.net/
https://web.de/
https://relay.firefox.com/
https://drive.google.com/drive/my-drive
https://dota2.gamepedia.com/Dota_2_Wiki

## Expected behavior

Websites should be darkened

## Actual behavior

Websites have default colors/are only partially darkened

## Screenshots

https://imgur.com/a/cmvuXN7

## System Information

- OS: Windows 10 64bit 20H2 
- Browser: 88.0a1 (2021-03-05) (64-Bit)
- Dark Reader Version: 4.9.29

**Comment by xcasxcursex** [comment]
Noticed this on ebay, I can see the addon try to theme the page, and as soon as the page load completes, boom it turns white.

I was using ebay.com.au. to test, I tried ebay.com and it was the same... Then ebay.co.uk, which was fine, the first time I visited it, then when I tried to take a screenshot for the bug report here, I went back, and it was broken there, too.

**Comment by Filip785** [comment]
Yep, can confirm too, example sites:

- rs.n1info.com
- nova.rs
- danas.rs

I tried to reinstall extension and it's still not working.

**Comment by xcasxcursex** [comment]
I notice GPU acceleration is not working. I've also seen sites work, then not work, then work again, with dark reader (eg wikipedia came up dark then light then dark again) Between that and the intermittent behaviour, I think this is just a broken build of FF.

**Comment by Gusted** [comment]
> I notice GPU acceleration is not working. I've also seen sites work, then not work, then work again, with dark reader (eg wikipedia came up dark then light then dark again) Between that and the intermittent behaviour, I think this is just a broken build of FF.

I've noticed this as well. Also code-wise seems to be some broken configuration. Give it ~2 days to get them fixed. I'd tried to run `mozregression` but didn't give much insight. Might be my special laptop being slow.

I will try to run it tomorrow again. Might be some good of help why as I cannot find 123 an bug filled about this.

**Comment by Gusted** [comment]
Hi all!

I'd tried to run mozregression while I noticed `2021-03-06` came out. It seems to be fixed and indeed was an faulty build after all.

Regards,
Gusted

**Comment by xcasxcursex** [comment]
> I'd tried to run mozregression while I noticed `2021-03-06` came out. It seems to be fixed and indeed was an faulty build after all.

Confirmed, at least for functionality of dark reader.

GPU acceleration is still broken, among a few other minor things.... I guess we'll have a bumpy ride getting past whatever they did in those past few builds.

**Comment by Gusted** [comment]
> GPU acceleration is still broken, among a few other minor things.... I guess we'll have a bumpy ride getting past whatever they did in those past few builds.

Mozillians would appreciate if you file an bug over at https://www.bugzilla.mozilla.org/

**Comment by Gusted** [comment]
Opening this in favor to track the issues with Firefox Nightly day-to-day especially combined with Dark Reader, as well for other problems.

**Comment by nkestrel** [comment]
Caused by [Bug 1360715](https://bugzilla.mozilla.org/show_bug.cgi?id=1360715), can get it working by toggling `dom.webidl.crosscontext_hasinstance.enabled` to `true`.

**Comment by gabrielambuehl** [comment]
FWIW, two days ago this also started happening on FF Android Nightly, likewise toggling dom.webidl.crosscontext_hasinstance.enabled alleviated it for now.

**Comment by danielzgtg** [comment]
I bisected this and found that it's fixed in master (4d268f35) since commit 1c1354dc. I tested on Firefox Nightly Android version `210310 17:03`. All 14 websites in this thread work.

**Comment by gabrielambuehl** [comment]
Remains broken for me in FF Android 20210312 unless I toggle dom.webidl.crosscontext_hasinstance.enabled (possibly it was only broken in 0311, definitely worked longer than on desktop)

![Screenshot_2021-03-13-10-57-44-303_org mozilla fenix](https://user-images.githubusercontent.com/38832083/111026654-a7c21600-83eb-11eb-8fa1-8ede81b0617a.jpg)
![Screenshot_2021-03-13-10-55-24-415_org mozilla fenix](https://user-images.githubusercontent.com/38832083/111026656-a8f34300-83eb-11eb-8242-5b97443faaf4.jpg)

**Comment by danielzgtg** [comment]
> it's fixed

> Remains broken

I meant the version in Git is fixed. The published version (tag `v4.9.29`) doesn't contain the fix

**Comment by Gusted** [comment]
Just be-aware if somehow that variable support PR fixed this issue(Which actually broke more websites than fixes issues). It can take some time before we publish a new version => https://github.com/darkreader/darkreader/pull/4291#issuecomment-797257540

**Comment by sharbet** [comment]
> Just be-aware if somehow that variable support PR fixed this issue(Which actually broke more websites than fixes issues). It can take some time before we publish a new version => [#4291 (comment)](https://github.com/darkreader/darkreader/pull/4291#issuecomment-797257540)

When the supposed fix arrives to Nightly, would I have to manually reset 
`dom.webidl.crosscontext_hasinstance.enabled`, or would it be set to its default boolean automatically?

**Comment by alexandru** [comment]
Confirming that the behavior still exists on the latest Firefox Nightly for Android, with Dark Reader 4.9.29.

To add to the list of websites affected:

- [translate.google.com](https://translate.google.com/)
- [instagram.com](https://www.instagram.com/)

Possible solutions that seem to work:

1. setting `dom.webidl.crosscontext_hasinstance.enabled` to `true`
2. changing the mode from *Dynamic* to *Filter* (can be done on a per-site basis)

I noticed that the "dynamic" mode is not mentioned in this thread. FYI the "Filter" and "Static" modes still work.

As a suggestion for future development, relying on `instanceof` checks on open types is always a bad idea, as it breaks encapsulation — although I am aware that this is just how people work in JavaScript, and maybe you had no choice. If you can find alternatives that don't rely on `instanceof`, maybe you should work with those alternatives.

Thanks for all your hard work.

![image](https://user-images.githubusercontent.com/11753/111980606-35e67c80-8b0f-11eb-93f1-c1d1ba2c2807.png)

**Comment by danielzgtg** [comment]
> `instanceof`

We can fix our `x instanceof Y` problems by replacing them with `x instanceof w.Y`, where `w` is the window object for the page containing `x`

**Comment by chromer030** [comment]
Reproducible on nightly 89.0 a1

**Comment by saschanaz** [comment]
Hi people, we at Mozilla fixed this issue in https://bugzilla.mozilla.org/show_bug.cgi?id=1697829 and confirmed the latest build now works as expected. Thank you @nkestrel and others for reporting the issue 💕

**Comment by Gusted** [comment]
> Thank you @nkestrel and others for reporting the issue two_hearts

And thank you for working on the fix 😄 and if it just happens to be an bug in nightly with dark reader in the future, don't mind to ping me as I could give some relevant information on how certain parts works.

So just for sakes to understand what the underlying problem is as the `suspect code` has change quite a bit between the comments on Bugzilla. Whereby even got spoken of exempting extension from the new cross-context instance behavior(which wasn't implemented after all). 

It seems their was some bug with the constructor type of CSSRules(when inserted from cross-context) wasn't matching when it had to be?

**Comment by saschanaz** [comment]
>It seems their was some bug with the constructor type of CSSRules(when inserted from cross-context) wasn't matching when it had to be?

Correct, it was a separate hidden bug where it couldn't find the correct context to wrap the rule objects. A general fix that can be applicable for all web pages (but for rare situations). 👍

**Comment by pablo-hp** [comment]
This work for me.
In Firefox Nightly, 
In about:config
In dom.webidl.crosscontext_hasinstance.enabled 
I changed from false to true 
And Work on most sites.

**Comment by xcasxcursex** [comment]
> In about:config
> In dom.webidl.crosscontext_hasinstance.enabled
> I changed from false to true

As far as I can see that isn't necessary any more since the latest builds, and if you've changed it, you can safely revert to the default setting.

**Comment by mobd** [comment]
In the latest Nightly 210323 17:01 (Build #2015800395) I still have this issue on github, youtube and other sites. Is the fix supposed to be in this version yet?

**Comment by pablo-hp** [comment]
> > In about:config
> > In dom.webidl.crosscontext_hasinstance.enabled
> > I changed from false to true
> 
> As far as I can see that isn't necessary any more since the latest builds, and if you've changed it, you can safely revert to the default setting.

Thanks for the feedback,
However, using version 210323 17:01 (build #2015800395) AC: 74.0.20210322143147 GV: 88.0a1-20210322093509 AS: 74.0.1, I am encountering several problems with YouTube and other sites.
YouTube is the site I use the most and yet it is not working properly with YouTube.
It only worked now, after doing the procedures I mentioned above.

In my case, for me, the bug still exists and persists.

**Comment by Gusted** [comment]
As I can see the fix was pushed to the 89 branch whereby Mobile is still on the 88 branch of Firefox, when it happens to be to bump firefox mobile to 89 branch the fix would be included.

**Comment by pablo-hp** [comment]
> As I can see the fix was pushed to the 89 branch whereby Mobile is still on the 88 branch of Firefox, when it happens to be to bump firefox mobile to 89 branch the fix would be included.

Cool.
Good to know.
Thanks.
