### ISSUE TITLE
[Feature Request (or bug?)] Option to exclude images from inverting (or a tweak setting)

### ISSUE THREAD

**Issue by godzfire** [darkreader/darkreader#7986]
# Feature Request

## Is this feature request related to a problem?
Potentially, it could be considered intended behavior or at the same time a bug.

## Screenshots
Use weather.com with the zip code 90210:
https://weather.com/weather/tenday/l/79a8aa24a1dbb73f308d77b3de429eef4da1cd0d83198c44757b11e3fea6dbf8

## Additional Context
For the most part, DarkReader is amazing and incredibly accurate. For 99% of the time, Dynamic mode is what I use because it's most compatible and pleasing to the eye. The amount of customization is excellent too to further tweak things (I'm on version 5 preview).

However there are certain sites where Dynamic gets a little too 'aggressive' with images. The weather.com example above shows it. With Dynamic mode on, it will make any icon that has a sun in it black. If you use a near black background like I do, it turns essentially invisible. The other themes don't necessarily have that problem on that site, but they also make the rest of the website look very poor, so really not an option.

It would be nice to have a feature/tweak/setting that could allow some customization that accomplishes this. That said, I do see there's a dev section which seems to allow you to do exclusions or addition via HTML, but as someone who's not intimately familiar with that sort of thing (and I feel completely out of joe user's knowledge), it would be nice to have that option somehow.

If this has already been implemented and I'm just not seeing it, I greatly apologize. Also if something like that would be a coding nightmare or impossibility I also totally understand that as well.

Thank you so much for this great and free product. I recommend it to everyone I know.

**Comment by godzfire** [comment]
Thank you for doing Sunny, but it seems that there are more that suffer from the same issue. Is there a way to disable/whitelist it for all of the weather conditions?

<img width="244" alt="Screen Shot 2022-01-20 at 6 15 18 PM" src="https://user-images.githubusercontent.com/2067820/150442653-5262aa89-cbe0-4a27-b20c-1948ec8ee8bc.png">
<img width="209" alt="Screen Shot 2022-01-20 at 6 15 26 PM" src="https://user-images.githubusercontent.com/2067820/150442656-c9da302e-2019-49fb-98a4-2f47edb3e2d7.png">

**Comment by Gusted** [comment]
> Thank you for doing Sunny, but it seems that there are more that suffer from the same issue. Is there a way to disable/whitelist it for all of the weather conditions?

Where can I find these icons? They already should be fixed in the next version.

**Comment by godzfire** [comment]
My apologies, you can see a variety of examples of them by using the 90210 address link here and show the monthly view:
https://weather.com/weather/monthly/l/79a8aa24a1dbb73f308d77b3de429eef4da1cd0d83198c44757b11e3fea6dbf8

![image](https://user-images.githubusercontent.com/2067820/152657436-cb625d4b-b17c-40e7-b064-05f6c4eac7bc.png)
![image](https://user-images.githubusercontent.com/2067820/152657444-c39e2aee-27e2-4c7b-9d53-5232c7b17fee.png)

**Comment by Gusted** [comment]
> My apologies, you can see a variety of examples of them by using the 90210 address link here and show the monthly view:

Those are already fixed, see: https://github.com/darkreader/darkreader#site-fixes

**Comment by godzfire** [comment]
I do have that enabled, and saw your original fixes come through, but not the rest how do I force a refresh? I've tried closing and reopening Chrome.

**Comment by Gusted** [comment]
> I do have that enabled, and saw your original fixes come through, but not the rest how do I force a refresh? I've tried closing and reopening Chrome.

You could use the "reset" button in the dev tools to force a new refresh.

**Comment by godzfire** [comment]
I did do a reset and nothing changed. Do I need to clear my cache, or maybe do you think those icons are coded separately than the larger ones?

Are you saying if you go to the link example I provided above, that you can see all the sunshine icons properly?

**Comment by godzfire** [comment]
I'm still not seeing the changes and seeing the sun icons properly and I've reset things. The sunny only icon was fixed. It's the others that still don't show properly. Can you double check everything is looks good on your end?

Site test: https://weather.com/weather/monthly/l/b26930a940b24ae18778d448a3c8d5375540d55c3c029a033c90dd7838ccea5f

<img width="772" alt="image" src="https://user-images.githubusercontent.com/2067820/155765134-23184c40-77a7-4deb-9ae0-16639d4aedc5.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/2067820/155765208-807e0a73-51b4-4e46-9e93-b5967b5fc146.png">

**Comment by Gusted** [comment]
It still has been the same for me, you have something going on with the user fixes, try to reset them in the dev tools of dark reader.
![image](https://user-images.githubusercontent.com/25481501/155771869-f17b942a-0fcb-444c-a8db-eefd711b8884.png)

**Comment by godzfire** [comment]
Reset Changes in Dev list, Apply and refresh; no change
Reset all of DarkReader to default and enable Sync Site Fixes; no change
Completely uninstall and reinstall DarkReader stock and enable Sync Site Fixes; no change
Run Chrome from a brand new profile, install DarkReader stock and enable Sync Site Fixes; no change

I'm very sorry but I'm not sure what else I could be doing wrong at this point.

**Comment by Gusted** [comment]
> Reset Changes in Dev list, Apply and refresh; no change Reset all of DarkReader to default and enable Sync Site Fixes; no change Completely uninstall and reinstall DarkReader stock and enable Sync Site Fixes; no change Run Chrome from a brand new profile, install DarkReader stock and enable Sync Site Fixes; no change
> 
> I'm very sorry but I'm not sure what else I could be doing wrong at this point.

What if you try manually copy and paste [the current fixes](https://github.com/darkreader/darkreader/raw/master/src/config/dynamic-theme-fixes.config) as a temporary workaround?

**Comment by godzfire** [comment]
Unfortunately that doesn't do it either. I don't understand. Both Filter and Static show the icons just fine.

If it helps, when the site reloads, for a split second, the icons appear proper, but then are 'darkened'.

**Comment by godzfire** [comment]
Unless I'm misunderstanding what I'm seeing in the config code, the current fixes don't include the changes that fix the other icons.

Here's the listing for weather.com:

INVERT
div[class*="DynamicMap"]
svg[name="arrow-up"]
svg[name="arrow-down"]
text[class*="DonutChart"]

IGNORE INLINE STYLE
[id^="svg-symbol"] *
svg[class*="alerts--"] *
#svg-symbol-sun

This is what it looks like with the above removed:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/2067820/155820320-762344b1-a636-44bc-b2af-ea44e97dcf4c.png">

This is what it looks like with the above added:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/2067820/155820377-4df26077-b7ce-41d8-ad2b-5649d98bdd61.png">

**Comment by godzfire** [comment]
Fixed it myself, changing '#svg-symbol-sun' to '#svg-symbol-*' corrects all the icons. If you want to include that in your config.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/2067820/155821004-5131dc40-71e0-4d2a-b288-28ef78011fb6.png">

**Comment by godzfire** [comment]
I honestly don't know then, I've just been trying to figure out how to fix it. It did something and it's held so far.
