### ISSUE TITLE
[Chrome] Dynamic only works after toggling twice on https://docs.python.org

### ISSUE THREAD

**Issue by soerenwolfers** [darkreader/darkreader#835]
I am using Dark Reader in Chrome 70.0.3538.77 with the "Dynamic" theme engine. 

When I open https://docs.python.org, the main frame is shown in white (there are some modifications in the background). This can be fixed by turning Dark Reader off and on again. 

Screencast: https://streamable.com/1br2s

**Comment by NickToporkov** [comment]
sane problem on https://docs.conda.io/

**Comment by ThisIsIsaac** [comment]
This is a really annoying problem... Any updates?

**Comment by glostis** [comment]
Hi,

I have the same issue on https://gdal.org/user/

If I am not mistaken, it seems that the websites listed above all have in common the fact that they were created using [sphinx](https://www.sphinx-doc.org/en/master/). Would there be something to look for in that direction?

Being a python developer, I land on such websites several times per day and it's a bit tedious to have to turn Dark Reader on and off for it to work...

**Comment by Gusted** [comment]
Diffrence between Before(-) and After(+)
https://pastebin.com/Y6thQgTg

**Comment by Gusted** [comment]
Just the placement of the darkreader--override is diffrent

**Comment by pranavmarla** [comment]
Reloading https://docs.python.org in the same tab also solves the issue. However, if I close the tab and then reopen it, the issue is back -- i.e. that first view whenever the tab is loaded is always wrong.

**Comment by Gusted** [comment]
Okay.
Their is a import rule to default.css only somehow that's empty?
In that import rule it has another import Rule to classic.css that contain the unstyled styles that dark reader can't reach I will see if we manually can fetch the style.

**Comment by Gusted** [comment]
[Test-Case.zip](https://github.com/darkreader/darkreader/files/4966908/Test-Case.zip)
Reproduceable test case. Uhm it's a chrome bug as firefox is having no errors with this.
I will discuss with the owner of Dark Reader, probably filling up a bug report that will be posted somewhere on the back log 🤷🏽‍♀️ 

left: Chrome (Bug is happening)
right: Firefox (How it should be)
![](https://i.imgur.com/Fp1iVcb.png)

**Comment by Exper1mental** [comment]
Same issue on Vivaldi (chromium-based)
![CdoFugoiSB](https://user-images.githubusercontent.com/14143235/89779230-e5209700-dadc-11ea-9952-e620bb1eed2e.gif)

**Comment by Gusted** [comment]
I will add this issue to our V5 road map.

**Comment by WoodpeckerBaby** [comment]
Is there an update on this issue? What's the plan?

**Comment by mattwelke** [comment]
Found the old, closed issue which suggested to create a new issue for each broken site. After reading the new issue template, I searched for "docs.python.org" and found this.

This is affecting me right now using Google Chrome. There is no problem with Firefox.

Chrome on page load:

![image](https://user-images.githubusercontent.com/7719209/104959037-4491a580-599f-11eb-946f-4451f487150c.png)

Chrome after toggling extension:

![image](https://user-images.githubusercontent.com/7719209/104959087-5d9a5680-599f-11eb-8678-7c81a6eb8200.png)

Firefox on page load:

![image](https://user-images.githubusercontent.com/7719209/104959098-69861880-599f-11eb-8146-d1de59104383.png)

Versions:

Chrome: Version 87.0.4280.141 (Official Build) (64-bit)
Firefox: 84.0.2 (64-bit)

**Comment by norweeg** [comment]
I have this problem in all browsers on all OS.  Firefox, Chrome, Edge, Windows, MacOS, Linux, does not matter.  I also have a similar problem on MSN News pages too

**Comment by dsethlewis** [comment]
The same issue occurs for me on palletsprojects.com, which, like the other Python documentation sites mentioned, is built on Sphinx. Changing the theme engine to Filter+ is a passable workaround for docs.python.org but is less attractive on other sites. Not all Sphinx-based sites cause the problem, though--e.g., readthedocs.io.

**Comment by Gusted** [comment]
#3552 was a bit unreliable as "fix", #6102 should fix the issue 100% of the time - render engines are weird.

**Comment by Gusted** [comment]
#6102 has been merged and will be in the next release - no ETA as usual.

**Comment by tanay-pingalkar** [comment]
i faced this issue on all sites, it asked me to reload page to apply dark mode, then i found that it was allow to run on only click. So i made it allow for all sites.

**Comment by davetapley** [comment]
@Gusted looks like there's been a few releases since this was merged, but I still see it on e.g. https://docs.python.org/3/library/unittest.mock-examples.html with`4.9.45`. Can you confirm? 🤔

**Comment by norweeg** [comment]
@davetapley that site looks fine to me Microsoft Edge Version 98.0.1108.56 (Official build) (64-bit) with Dark Reader version 4.9.45

**Comment by Gusted** [comment]
Also looking good on my side.

**Comment by davetapley** [comment]
Yep, working for me now.
How peculiar, sorry for the noise 🙈
