### ISSUE TITLE
[Bug] Dropdown menus are styled poorly

### ISSUE THREAD

**Issue by RheingoldRiver** [darkreader/darkreader#8351]
# Bug Report

## Website Address
https://www.goodreads.com/review/edit/52379336?report_event=true&survey=1

## Bug Description
Dropdown menus are illegible when using dark reader, even when there's no applicable userChrome.css interfering. (Relevant selectors: menulist, menupopup, menuitem.)

## Steps To Reproduce
1. Go to a website with dropdown menus
2. Expand a dropdown menu.

## Expected Behavior
Dropdown menus should be dark themed

## Actual Behavior
Dropdown menus are illegible

## Screenshots
(Note, I deleted all my userchrome.css for these screenshots)

With dark reader:
![image](https://user-images.githubusercontent.com/18037011/156832710-bb5711d6-e316-4aed-b487-1e4e1cab7d2a.png)

Without dark reader, using [this Firefox theme](https://addons.mozilla.org/en-US/firefox/addon/matte-black-red/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser)
![image](https://user-images.githubusercontent.com/18037011/156832788-8a9d891f-b9d6-4df7-b188-e78de2abe98b.png)

----

The same two screenshots if I use default Light theme:

With dark reader:
![image](https://user-images.githubusercontent.com/18037011/156832892-666f1b4c-54c1-4de0-a5bf-f5a31f1ebdf9.png)

Without:
![image](https://user-images.githubusercontent.com/18037011/156832848-63b4dbdc-efa7-493d-921a-f733b694d521.png)

## System Information

- OS: Windows
- Browser: Firefox 96.0.3
- Dark Reader Version: 4.9.45

## Additional Context
I think this is a regression within the last 10 or so Firefox versions, I'm *pretty* sure this used to be fine, and then I did a bunch of updates all at once, and now it's not fine.

**Comment by Gusted** [comment]
Could you try disabling all firefox themes? Also you might want to disable dark reader styling such elements:


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    under Theme click See all options, Font's & more -> Style system controls

**Comment by RheingoldRiver** [comment]
Hmm, even with System theme - auto, and that preference changed (so styling system controls is "No") (and again no userChrome.css) it looks like this:

![image](https://user-images.githubusercontent.com/18037011/156845118-1cab506c-f0e8-48c0-947f-393551edcaa3.png)

I may have made a mistake filing this as a general bug, though: Previously, I've had problems on multiple websites (Etsy and Jira were others) but now with all of these settings I'm only reproducing this on Goodreads, so I'm thinking now this may be a Goodreads-specific bug. Would you like me to close this and open a new ticket?

**Comment by Gusted** [comment]
I'm not able to reproduce this bug.... This really seems to be a system issue(as these are directly styled from the OS's preferred colors)

**Comment by RheingoldRiver** [comment]
I think DarkReader is applying this style, even when I uncheck the thing about styling system things:
![image](https://user-images.githubusercontent.com/18037011/156853583-74db6abe-48b8-4869-ad3f-f606ffd53e37.png)

**Comment by Gusted** [comment]
That's weird, on my side the colors are correctly dark/white... 

I've tried to fiddle around and it doesn't seem like I'm even able to set any other colors, they seems to be forced by Firefox to a specific color(as given by your system).

**Comment by RheingoldRiver** [comment]
Just in case you're not aware, these screenshots are taken using the [browser toolbox inspector](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox) not the normal DevTools - afaik you can't normally inspect the dropdown menus with normal DevTools.

Possibly relevant - in about:config, I've set `layout.css.prefers-color-scheme.content-override` to 2 so I'm overriding my system default to dark mode, though Windows is already dark mode so that shouldn't make a difference. Also, earlier today it was 3, I just tried changing it to 2 to see if that made a difference, and it didn't seem to.

That `content-select-background-image variable` that I screenshotted is only present on a `menuitem` when DarkReader is enabled on the page, so I'm almost certain it's caused by this extension. Are you running the same version that I have? Is it possible the "don't apply on system elements" just isn't working properly on my version and by updating later this will be resolved?

**Comment by Gusted** [comment]
I'm not really sure what's going on now, because for what it looks to me is that dark reader on my machines aren't touching or modifying those select options(even when forced) and Firefox still displays the same style. I don't see any of the mentioned modification happening.


Y

> , so I'm almost certain it's caused by this extension. Are you running the same version that I have? Is it possible the "don't apply on system elements" just isn't working properly on my version and by updating later this will be resolved?

Firefox Nightly, Dark reader v4.9.45

**Comment by RheingoldRiver** [comment]
Just to check, are you logged in & testing on the Goodreads site? Because I think it's only on this one website that it's broken.

If you can't reproduce still, then I guess we can close this, since I have fixed the problem, and maybe re-open it if someone else has the same issue later.

**Comment by Gusted** [comment]
> Just to check, are you logged in & testing on the Goodreads site? Because I think it's only on this one website that it's broken.

Yup logged in and also using the dropdown for the reading dates:
![image](https://user-images.githubusercontent.com/25481501/156921868-25cc3bd3-5439-4d84-8dff-31e3a95bd189.png)

Honestly, It rather sounds like if I had a Window machine lying around that I also would be reproducing the bug as these kind of elements are highly controlled by the browser + OS.

**Comment by edodson84** [comment]
hi the fix is to add styling to the options as follows:
option {
	background-color: var(--darkreader-neutral-background) !important;
}

**Comment by Pierrounator** [comment]
Hi, this fix doesn't fully work actually, I still encounter the same problem that the OP had. Dropdown menus texts are white on very light-grey background.
I can't post the website since it's an intranet. I use the latest Firefox on W11.

Any way to fix it? :(
