### ISSUE TITLE
[Safari] Mermaid Diagrams's font is too dark,but in chrome it is good

### ISSUE THREAD

**Issue by A1bertWong** [darkreader/darkreader#855]
![image](https://user-images.githubusercontent.com/28760834/48825326-04740f80-eda2-11e8-8a65-d12bda22d4c3.jpeg)
![image](https://user-images.githubusercontent.com/28760834/48825377-2a011900-eda2-11e8-90b7-d88df2dba3a3.jpeg)

**Comment by Gusted** [comment]
Resolved

**Comment by Leowang628** [comment]
> Resolved

> Resolved

No Resolved, please go to this website to check：https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgQWxpY2UtPj4rSm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_XG4gICAgQWxpY2UtPj4rSm9objogSm9obiwgY2FuIHlvdSBoZWFyIG1lP1xuICAgIEpvaG4tLT4-LUFsaWNlOiBIaSBBbGljZSwgSSBjYW4gaGVhciB5b3UhXG4gICAgSm9obi0tPj4tQWxpY2U6IEkgZmVlbCBncmVhdCFcbiAgICAgICAgICAgICIsIm1lcm1haWQiOnt9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ

**Comment by Yash-Singh1** [comment]
Same here:
![Screenshot from 2020-12-06 19-59-18](https://user-images.githubusercontent.com/53054099/101307954-8acee300-37fd-11eb-884a-ae345e81b4e5.png)

The arrows seem to disappear on Chrome. This is not only on Safari.

**Comment by Leowang628** [comment]
> Same here:
> ![Screenshot from 2020-12-06 19-59-18](https://user-images.githubusercontent.com/53054099/101307954-8acee300-37fd-11eb-884a-ae345e81b4e5.png)
> 
> The arrows seem to disappear on Chrome. This is not only on Safari.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/28760834/101308191-420e3d00-3884-11eb-8a1e-4c6a74e57b56.png">
But it still doesn’t work for me, do I need to adjust any configuration?

**Comment by Leowang628** [comment]
> > Same here:
> > ![Screenshot from 2020-12-06 19-59-18](https://user-images.githubusercontent.com/53054099/101307954-8acee300-37fd-11eb-884a-ae345e81b4e5.png)
> > The arrows seem to disappear on Chrome. This is not only on Safari.
> 
> <img alt="image" width="473" src="https://user-images.githubusercontent.com/28760834/101308191-420e3d00-3884-11eb-8a1e-4c6a74e57b56.png">
> 
> But it still doesn’t work for me, do I need to adjust any configuration?

I downloaded it in the AppStore, the version is 1.4.2

**Comment by alexanderby** [comment]
Looks good now
<img width="566" alt="Screenshot 2024-01-16 at 10 52 12" src="https://github.com/darkreader/darkreader/assets/9638588/7046645d-2866-4acf-a1c7-ec9386530353">
