### ISSUE TITLE
[Broken Website] Google Docs negative images

### ISSUE THREAD

**Issue by Pseudonomenclature** [darkreader/darkreader#8730]
# Broken Website Report

## Website Address
https://docs.google.com/document/u/0/
(any Google Doc with images)

## Steps To Reproduce
- Go into any Google Docs document with images in it. (Imported by any means)
-->

## Problematic Observation
Images will be the negatives of themselves. Black becomes white and all other colors likewise reverse.

## System Information
- OS: Windows 10
- Browser: Chrome, Version 100.0.4896.127
- Dark Reader Version: 4.9.47

## Additional Context
This was not an issue just a couple of days ago.

**Comment by Gusted** [comment]
Are you using Dark reader's Filter mode by any chance?

**Comment by Pseudonomenclature** [comment]
> Are you using Dark reader's Filter mode by any chance?

No, the mode is set to Dynamic.

**Comment by ColorMeBrackets** [comment]
I am having the same issue. It occurs for me in Filter, Filter+, and Dynamic (my default), while Static simply keeps the main document body non-darkened (which is non-preferable on my end). See captured images below for examples, corresponding image under each number.
1. Filter
![image](https://user-images.githubusercontent.com/86329857/164997156-6cfb18b0-ee45-470d-ab54-a6a505b462c5.png)
2. Filter+
![image](https://user-images.githubusercontent.com/86329857/164997218-de78e9e0-c43d-4748-ad40-dbe41d6d40f9.png)
3. Static
![image](https://user-images.githubusercontent.com/86329857/164997270-5c1a1a67-3a29-4050-899b-8cb4d265cb12.png)
4. Dynamic
![image](https://user-images.githubusercontent.com/86329857/164997296-76ea003e-8db7-4abd-b60d-d6af7694b574.png)
I am not quite sure how to use the Developer Tools to manually fix things, I'm not too experienced with programming and don't want to risk breaking anything on my end.

**Comment by Gusted** [comment]
If you open the devtools(ctrl + shift + c), it should let you to hover over an element. Please click on the inverted image. This would now show which image it is in the dev tools. Please make a screenshot of the CSS of that element(please include the one that has a `filter` property).

**Comment by alexanderby** [comment]
<img width="914" alt="Screen Shot 2022-04-25 at 17 34 47" src="https://user-images.githubusercontent.com/9638588/165133748-b26d11a6-63f2-4569-9127-7d4a41660765.png">
Seems like they started using the Canvas in Chrome version. I see no solution here.

**Comment by Gusted** [comment]
That's a big unfortunate that they are switching to canvas. An existing theory with google spreadsheets, which already made this change a while back was to hack into the canvas and do some proxy coloring, but given the larger customization of google docs, that would be a no-go and just ask for more problems.

Going to pin this and hopefully prevent many issues from opening about this. Maybe someone creative can come up with a workaround or solution, but this is a plain and old situation where we can only do so-much as a generic extension.

**Comment by yorgos-s** [comment]
Any possibility to have an experimental option to reverse canvas' colors per pixel? Maybe this will create other issues (like latency) but it could be a temporary solution for canvas based sites.

https://stackoverflow.com/questions/39048227/html5-canvas-invert-color-of-pixels

**Comment by Gusted** [comment]
> Any possibility to have an experimental option to reverse canvas' colors per pixel? Maybe this will create other issues (like latency) but it could be a temporary solution for canvas based sites.

And how should the code know what to revert? If we revert the whole canvas, you will not have dark mode anymore.

**Comment by yorgos-s** [comment]
> > Any possibility to have an experimental option to reverse canvas' colors per pixel? Maybe this will create other issues (like latency) but it could be a temporary solution for canvas based sites.
> 
> And how should the code know what to revert? If we revert the whole canvas, you will not have dark mode anymore.

Ok now I understand - The document itself is a canvas - what a pity - dark reader was the perfect match for google docs - thanks for your reply!

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Why does utilisation of canvas prevent remediation of this problem?

**Comment by Gusted** [comment]
A [canvas element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas) is like a real canvas. You can draw a lot of things on it, triangles, images, people, text etc. As the artist, you know the process of what happened, how it was made and which elements were used.

As a viewer, you can only think abstractly about the canvas. You see the end result. But you don't know if a certain pixel on that canvas was made, is it meaning that it's part as a text? Or is actually part of a face? Humans are great at this! But a computer isn't, at least unless you want to let your GPU scream.

So the problem is, Dark Reader sees the end result and don't know if that canvas contains a picture or not and if it knows it contains a picture, it should know the picture boundary. The only action that Dark Reader can use on this canvas, is to invert it, as it's exposed as one element.

**Comment by Cippman** [comment]
Same issue, but just since few days ago. Not only with images but with already dark-backgrounded docs!

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@Gusted, I am thankful. What you have described appears to me to be identical to a picture, which was why I was confused; why create another element if it acts identically? I shall research.

**Comment by brmonaghan** [comment]
Same here, Wikipedia logo is dark inverted. Also, the colors are inverted in PDFs as well.

**Comment by Gusted** [comment]
> Wikipedia logo is dark inverted. Also, the colors are inverted in PDFs as well.

Those aren't related to the google docs issues. Please open a different issue about those.

**Comment by brmonaghan** [comment]
> > Wikipedia logo is dark inverted. Also, the colors are inverted in PDFs as well.
> 
> Those aren't related to the google docs issues. Please open a different issue about those.

ok, i will open new issue.

**Comment by Cook66** [comment]
I have the same issue in Google Docs and Sheets. Colors of PNG images are inverted in Dynamic, Filter and Filter+ modes, Filter also desaturates the images.

Static does not invert the colors, but it also does not change the document background from white. The interface parts that does turn dark has poor contrast, looks very odd and gets gray boxes around the scroll bar and at the bottom of the page. It is basically not usable.

Swapping to static lets me see images as they should be while keeping some parts of the page dark, so I guess that's something at least.

**Comment by yorgos-s** [comment]
The best solution worked for me is to swap to static and then invert the colors of backgrounds + fonts manually (actually is pretty easy even if you have a ton of documents like I do). There minor issues like you cannot see the colors of the color pallete when you cange the text font for instance or if you create a comment (CTRL+ALT+M) a grey area in th e whole document appears , but apart from these minor bugs works fine.

**Comment by Langboule** [comment]
> The best solution worked for me is to swap to static and then invert the colors of backgrounds + fonts manually (actually is pretty easy even if you have a ton of documents like I do).

Would you mind sharing your style ? I have no CSS knowledge, so I can't do it manually.

**Comment by yorgos-s** [comment]
> > The best solution worked for me is to swap to static and then invert the colors of backgrounds + fonts manually (actually is pretty easy even if you have a ton of documents like I do).
> 
> Would you mind sharing your style ? I have no CSS knowledge, so I can't do it manually.

No CSS needed. Just follow [this ](https://www.youtube.com/watch?v=h0oMSPa2jqc&ab_channel=TechInsider)guide (after 1.13)   - tip: to have permanent font color white: -with the font changed to white selected)  go to  format--> paragraph and styles --> normal text --> update normal text to match

**Comment by dennisklad** [comment]
Hello, was this fixed in an other issue?

For me it looks like this:

Light:
![image](https://user-images.githubusercontent.com/53832177/193626650-5cd9f4b3-27dc-43f8-a67f-153cbe11311b.png)

Dynamic / Filter:
![image](https://user-images.githubusercontent.com/53832177/193626910-b4f160e6-b31d-4caf-87b4-331124ddd2d4.png)

Static:
![image](https://user-images.githubusercontent.com/53832177/193626879-8f818c68-2375-466a-b30e-3f91be29e81d.png)

Is there any solution? Thanks!

**Comment by patjgll** [comment]
Tested today 
Google Docs has inverted images
Windows 10, dark reader (last version) 4.9.58
Problem on Chrome and family (opera, vivaldi, brave) last version
No problem on Firefox, last version

Linux Mageaia 8 (last version) and  dark reader (last version) 4.9.58
Problem on Chrome and family (opera, vivaldi, brave) last version
No problem on Firefox, last version

**Comment by patjgll** [comment]
Tested today 
Google Docs has inverted images
Windows 10 (up to date), dark reader (last version) 4.9.58
Problem on Chrome and family (opera, vivaldi, brave) last version
No problem on Firefox, last version

Linux Mageaia 8 (last version) and  dark reader (last version) 4.9.58
Problem on Chrome and family (opera, vivaldi, brave) last version
No problem on Firefox, last version

**Comment by ortiza5** [comment]
Since Firefox still gets served the HTML structure with real `img` tags, you can use a User-Agent String switcher extension to impersonate Firefox and get the working HTML.

It might stop working if Google decides to serve the same version between Chromium and Firefox, but it works for now.

**Comment by livingstonlarus** [comment]
Hello. Based on @ortiza5 suggestion, wouldn't it be possible for the extension to intercept the requests made to docs.google.com and replace the Chrome user agent string to Firefox? This would allow to keep browsing the rest of the web with the user agent untouched.

**Comment by livingstonlarus** [comment]
Tested @ortiza5 suggestion and it works. I installed https://chromewebstore.google.com/detail/user-agent-switcher/kchfmpdcejfkipopnolndinkeoipnoia

But by default you only have Firefox 33, which will trigger a message from Google Docs that your browser is no longer compatible.

1. Go to the User Agent Switcher extension options, in the Custom User Agents tab, and add a more recent custom user agent. For example:
New User-agent name: Mac Firefox 121
New User-Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
Indicator Flag: FFM
Then click the Add button.

2. Stay in the extension options, go to Permanent Spoof List tab, and add the Google Docs domain:
Domain: docs.google.com
User-Agent String: Mac Firefox 121 (or the user agent you added on step 1)
Then click the Add button.

Now when you'll go open a doc at https://docs.google.com/document/ or a spreadsheet at https://docs.google.com/spreadsheets/ User Agent Switcher will trigger the Firefox user agent. But it will remain the default Chrome user agent for all other websites.

And images in Google Docs no longer show inverted colors when Dark Reader is on.

**Comment by livingstonlarus** [comment]
I noticed that some fonts do not render properly when using the Mac Firefox 121 user agent. Look at the paragraph written with Roboto Mono.

<img width="838" alt="Screenshot 2023-12-21 at 11 26 10" src="https://github.com/darkreader/darkreader/assets/55496551/e836fec9-dcbc-4cd5-9935-e9902311abe7">

It does not happen with Mac Firefox 33. But then you have the browser no longer supported warning.

<img width="836" alt="Screenshot 2023-12-21 at 11 25 31" src="https://github.com/darkreader/darkreader/assets/55496551/6e4bf283-6755-4a13-8fc5-fbe603a8e97a">

It's up to you to choose what's less annoying. I prefer the fonts to render properly so I'll stay with 33.

Maybe someone will find a user agent or other workaround that gets both issues fixed!

**Comment by drizztguen77** [comment]
Followed @livingstonlarus comment and it works. I'm on Windows so had to use the Windows user-agent string instead. For anyone needing it, here is the info:

New User-agent name: Windows Firefox 122
New User-Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
Indicator Flag: FFW

**Comment by Dverp** [comment]
THANK YOU - Ortiza's suggestion with @livingstonlarus instructions are the answer.  

On Windows, so using the following posted by [drizztguen77](https://github.com/drizztguen77): 
   New User-agent name:  Windows Firefox 122
   New User-Agent String:  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
   Indicator Flag:  FFW

I have been looking for an answer to this incredibly annoying issue every couple months for at least a year. 

The "Mac Firefox 121" does work on Windows, but right after saw "Windows Firefox 122" and switched to that, and will find out if that avoids the font issue @livingstonlarus pointed out, assuming it could also affect a windows machine.

**Comment by Chrysaloid** [comment]
I've found out that Firefox 106 doesn't give the "old browser warning" and also displays fonts correctly.

New User-agent name: Firefox 106
New User-Agent String: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Fedora/36 (XFCE) Firefox/106.0
Indicator Flag: FFW

I know it says Linux and Fedora but even though I'm on Windows - it works ¯\_(ツ)_/¯

**Comment by mayafrog** [comment]
Is this still working? Just tried on Chrome `x86 v126.0.6478.183` on Windows 11 in all modes + refresh in between with the following `ua` supplied above:
- Windows Firefox 33
- Windows Firefox 122
- Firefox 106

**Comment by unleashed7** [comment]
Doesn't seem to be working on Firefox anymore

**Comment by GitJez-alt** [comment]
Any updates with this?

**Comment by bkmdev** [comment]
> The following userscript tricks Google Docs into rendering the document as it does in Firefox. This causes images to be rendered as `<img>` elements instead of using `canvas`, while text continues to be rendered using canvas.
> 
> ```
> // ==UserScript==
> // @name         Force Google Docs Canvas Fallback
> // @description  Spoofs Firefox user agent to make Google Docs stop using canvas for images, while still using canvas for text rendering
> // @version      0.0.1
> // @match        https://docs.google.com/*
> // @run-at       document-start
> // ==/UserScript==
> 
> navigator.__defineGetter__("userAgent", () => "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0");
> ```
> 
> The above User-agent switcher extensions in prior comments do not work because they only modify the HTTP User-Agent header. They do not override the `navigator.userAgent` property in JavaScript, which is what Google Docs actually checks as of this writing.
> 
> A couple of alternative extensions that do support this behavior are:
> 
> * [UserAgent-Switcher (GitHub)](https://github.com/ray-lothian/UserAgent-Switcher), which can override navigator.userAgent at the JavaScript level.
> * [User-Agent Switcher by BrowserNative](https://browsernative.com/user-agent-switcher-extension/), which supports removing or modifying navigator properties entirely.

Thanks for the suggestions.  Tried all 3 methods in MacOS + Chrome v137 but none of them seem to work.  I even tried removing `navigator.userAgent` via "Disable certain navigator Properties" option in [User-Agent Switcher by BrowserNative](https://browsernative.com/user-agent-switcher-extension/), but it just causes the below error in a modal popup 🙁 :  

![Image](https://github.com/user-attachments/assets/b867c916-5b8b-4b73-a83b-0f1869928d50)

Does this workaround still work for anyone?  or has Google blocked this method as well? 😞 (sad that they so aggressively try to prevent accessibility-type user-control over their own browser!)

**Comment by snaphat** [comment]
> > The following userscript tricks Google Docs into rendering the document as it does in Firefox. This causes images to be rendered as `<img>` elements instead of using `canvas`, while text continues to be rendered using canvas.
> > ```
> > // ==UserScript==
> > // @name         Force Google Docs Canvas Fallback
> > // @description  Spoofs Firefox user agent to make Google Docs stop using canvas for images, while still using canvas for text rendering
> > // @version      0.0.1
> > // @match        https://docs.google.com/*
> > // @run-at       document-start
> > // ==/UserScript==
> > 
> > navigator.__defineGetter__("userAgent", () => "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The above User-agent switcher extensions in prior comments do not work because they only modify the HTTP User-Agent header. They do not override the `navigator.userAgent` property in JavaScript, which is what Google Docs actually checks as of this writing.
> > A couple of alternative extensions that do support this behavior are:
> > 
> > * [UserAgent-Switcher (GitHub)](https://github.com/ray-lothian/UserAgent-Switcher), which can override navigator.userAgent at the JavaScript level.
> > * [User-Agent Switcher by BrowserNative](https://browsernative.com/user-agent-switcher-extension/), which supports removing or modifying navigator properties entirely.
> 
> Thanks for the suggestions. Tried all 3 methods in MacOS + Chrome v137 but none of them seem to work. I even tried removing `navigator.userAgent` via "Disable certain navigator Properties" option in [User-Agent Switcher by BrowserNative](https://browsernative.com/user-agent-switcher-extension/), but it just causes the below error in a modal popup 🙁 :
> 
> ![Image](https://github.com/user-attachments/assets/b867c916-5b8b-4b73-a83b-0f1869928d50)
> 
> Does this workaround still work for anyone? or has Google blocked this method as well? 😞 (sad that they so aggressively try to prevent accessibility-type user-control over their own browser!)

Tested on a clean install of Chrome Windows build 137.0.7151.69 (it presumably shouldn't matter which OS you are using though) with the newest revision of Dark Reader and it appears to be still working.

It's not something Google should be able to _block_, as the whole reason they are doing a fallback is because certain browsers either have performance issues or do not work with canvas images. They are the ones who implemented the fallback code path. So, if it stops working it implies, they have removed their own fallback code.

Anyway, in your case there are some possibilities I can see:
1. You are getting served newer code by google that does not have the old fallback
2. The code is detecting the OS and taking an alternate code path -- seems unlikely
3. The script isn't running
4. The script is running too late
5. another extension, plugin, etc. is interfering with the operation in some way

The error you are getting when removing the userAgent field is expected. I'm not actually sure _why_ I mentioned the bowsernative extension, because I believe all you can do with it IS remove the field and if you do, it breaks google docs completely (as you saw).

I just put this up user script up the other day, but it's literally the same thing as the above 1-liner user script above, so I don't believe it is going to help with whatever issue is happening in your case:
https://github.com/snaphat/google-docs-image-rendering-fallback

**Comment by sheetcakeghost** [comment]
As of today, from my experience on windows 11 vivaldi, the user agent fix is temporary. It works for a moment, but then the browser refreshes itself and it's using canvas for images again. I can't seem to prevent it from refreshing.

This is specifically for spreadsheets, as I use [another extension](https://docsafterdark.com) for dark modeing google documents (and I have no other extensions that touch docs.google.com/spreadsheets). This other extension has no trouble keeping images un-inverted, but it only works for documents.
