### ISSUE TITLE
Not working with local URLs

### ISSUE THREAD

**Issue by scooter3** [darkreader/darkreader#882]
Is there a way to get darkreader to work with local URLs?

**Comment by mikkelam** [comment]
I have a jupyter notebook running on localhost:8888 which works just fine

**Comment by alexanderby** [comment]
I think you mean file URLs? Open chrome://extensions page, under Dark Reader click "Enable access to file URLs".

**Comment by scooter3** [comment]
No, not file URLs. Addresses like 192.168.1.xxx

**Comment by alexanderby** [comment]
Then it should work. Check if there are any errors in console, try switching between Dynamic, Filter and Static modes.

**Comment by eadsjr** [comment]
Your instructions to enable file urls helped me. This should be documented in the UI if it isn't already. Maybe something that pops up the first time in a session you navigate to a local file page.

**Comment by Gusted** [comment]
We already fixed this issue with IP's

**Comment by scooter3** [comment]
Is there a setting for this? I'm still not seeing it.

**Comment by Gusted** [comment]
@scooter3 just use the site toggle like normally.

**Comment by SLCH** [comment]
Still an issue for me.
Stays untogglable with x in address - no reaction on mouse click or keyboard combo.
Access to file URLs is enabled.
https://i.imgur.com/bkt3niS.png

**Comment by Gusted** [comment]
> Stays untogglable with x in address - no reaction on mouse click or keyboard combo.

Check your site list, it could be that the main domain is already in their and than you can't enable/disable subdomains/ports(know issue that would be fixed by #2517)

**Comment by SLCH** [comment]
Yep, it was in site list. After removing, all worked. Thanks @Gusted  !
Don't remember adding it there but not sure on that part.

**Comment by alexcode9** [comment]
This bug might still be present for specific IP's maybe the way the url is parse is still flawed... I had 192.168.0.108 not working but in site list only 192.168.0.1 was present, once I removed that .108 started working again.

**Comment by sevketufuk** [comment]
> This bug might still be present for specific IP's maybe the way the url is parsed is still flawed... I had 192.168.0.108 not working but in site list only 192.168.0.1 was present, once I removed that .108 started working again.

I got an app running on 192.168.0.178 and there is no way to enable Dark Reader

**Comment by bslote** [comment]
This issue 100% still exists as of 4.9.57. If `192.168.1.1` is in the site list it will trigger a false positive on `192.168.1.111`

**Comment by cvsickle** [comment]
Confirming the issue described by @alexcode9, @sevketufuk, and @bslote is still present in version 4.9.64. I'm on Firefox 114.0.2

**Comment by ohare93** [comment]
I just fixed this issue, but it was my own fault. I have a server at 192.168.x.x and I did not want that to be DarkMode'd, so it got put in the ignore list for this extention. But then one of my running apps at 192.168.x.x:8000 *I did* want to have DarkMode'd, yet it would seemingly not do so from the popup. Removing the original rule fixed it. Though I am left with the setup of one is not the way I want 😞

**Comment by d-atif** [comment]
I am trying two URLs: 1) http://127.0.0.1:8501/ ("localhost" as well) and 2) http://172.27.187.25:8501/ and I can't add neither to the not inverted site list. I keep pressing enter and clicking, doing what I usually do when adding sites but it doesn't get added to the list. I have only 3 sites added like kaggle, github and youtube.

**Comment by MaxRev-Dev** [comment]
I had the same issue. I don't know why, but my "localhost:4000" was not working before I changed from "Non invert listed" to "Invert listed". Kinda, It was randomly set. Try removing your localhost URL from that list and switch to the inverted one instead.

<img width="260" alt="image" src="https://github.com/darkreader/darkreader/assets/24393967/c22aff9e-ca5a-4768-9a5b-9565b323fb5b">

<img width="258" alt="image" src="https://github.com/darkreader/darkreader/assets/24393967/7cb86efd-a587-4d94-b86c-e35b72aa8117">

**Comment by shuantsu** [comment]
> I had the same issue. I don't know why, but my "localhost:4000" was not working before I changed from "Non invert listed" to "Invert listed". Kinda, It was randomly set. Try removing your localhost URL from that list and switch to the inverted one instead.

the same happens to me.

I always use "not invert listed" because I want to have dark reader on by default, but turn it off on sites that have dark mode implemented.

but for localhost:5000 as soon as I disable the dark mode I can't enable it anymore. the only way is:

1. switching to "invert listed only"
2. turn dark mode on and come back to "not invert listed"
3. remove it from the list.
