### ISSUE TITLE
[Bug] Graphical Bug After Update

### ISSUE THREAD

**Issue by Jw-Tan** [darkreader/darkreader#9516]
# Bug Report

## Website Address

Various website

## Bug Description

Image/graphics are missing after updated to 4.9.54

## Steps To Reproduce

- Go to google.com and do any search.
- Whole page is blank. However, mousing over the page reveals the links are there and can be clicked (at bottom of the page seen in screenshot below).
- Go to google.com and do any image search.
- Image results are missing.
- Go to youtube.
- Almost whole page is blank.

## Expected Behavior

Websites display correctly.

## Actual Behavior

Other than the websites listed above, pretty much every other websites exhibit some issue. This includes websites that I have and have not added to the dark reader filter. Once I used a private window or disabled this extension, pages render correctly. I have tried removing the extension and adding it back, but the problem remains. Opening the dark reader menu does not work, it will keep loading forever.

## Screenshots

![google - bug](https://user-images.githubusercontent.com/16812619/183942659-d7e490a0-fcab-464c-90ce-80dc98827c62.jpg)
![google cat - bug](https://user-images.githubusercontent.com/16812619/183942827-0441b290-b802-4964-8a34-a272157c5b39.jpg)
![youtube - bug](https://user-images.githubusercontent.com/16812619/183942847-8d236d67-2703-486e-a6f9-e1eb4bc1a854.jpg)
![loading bug](https://user-images.githubusercontent.com/16812619/183943226-46f87b47-aee0-4f72-a628-d1b3d064bba2.jpg)

## System Information

- OS:  Windows 10
- Browser:  Vivaldi 3.8.2259.42
- Dark Reader Version:  4.9.54

**Comment by Gusted** [comment]
Hi @Jw-Tan!

Could you open the devtools(ctrl + shift + i) and check if there are any reported errors in the console?

**Comment by Jw-Tan** [comment]
Here you go.

![console](https://user-images.githubusercontent.com/16812619/183946665-2db23633-95ea-4c5b-a098-0d2f4f6e39d1.jpg)

**Comment by Gusted** [comment]
Okay, this is fixed by #9515 a new version with this fix will be released soon.

**Comment by jenda69** [comment]
I have the same issue on Vivaldi side bar. It already happened a year ago #6842. Hopefully the fix for Opera fixes Vivaldi too.

**Comment by Gusted** [comment]
Pinning the issue.

**Comment by everurstruly** [comment]
The bug still exists. I had to disable and re-enable. I'm on Edge Browser [Version 136.0.3240.92 (Official build) (64-bit)]

**Comment by alexanderby** [comment]
@everurstruly Please share an error message from the console (index.js file) if it happens again.
